### ISSUE TITLE
Fails with "jq: not found"

### ISSUE THREAD

**Issue by nedsociety** [AnimMouse/setup-rclone#2]
```
Run AnimMouse/setup-rclone@v1
  with:
    rclone_config: ***
Run $GITHUB_ACTION_PATH/scripts/download/Linux.sh
/__w/_actions/AnimMouse/setup-rclone/v1/scripts/download/Linux.sh: 3: jq: not found
Error: Process completed with exit code 127.
```

* Job:
```
runs-on: ubuntu-latest
container: python:3.10
```

* Step:
```
- name: Setup Rclone
   uses: AnimMouse/setup-rclone@v1
   with:
     rclone_config: ${{ secrets.RCLONE_CONFIG }}
```
